        

-- DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER(10) PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(100)
);


-- STUDENTS table
CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE,
    PHONE NUMBER(14),
    DEPARTMENT_ID NUMBER(10),
    CONSTRAINT FK_STUDENT_DEPT FOREIGN KEY (DEPARTMENT_ID) 
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


-- INSTRUCTOR table
CREATE TABLE INSTRUCTOR (
    INSTRUCTOR_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE,
    DEPARTMENT_ID NUMBER(10),
    CONSTRAINT FK_INSTRUCTOR_DEPT FOREIGN KEY (DEPARTMENT_ID) 
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


-- COURSES table
CREATE TABLE COURSES (
    COURSE_ID NUMBER(10) PRIMARY KEY,
    COURSE_NAME VARCHAR2(50) NOT NULL,
    CREDITS NUMBER(2),
    DEPARTMENT_ID NUMBER(10),
    INSTRUCTOR_ID NUMBER(10),
    CONSTRAINT FK_COURSE_DEPT FOREIGN KEY (DEPARTMENT_ID) 
    REFERENCES DEPARTMENT(DEPARTMENT_ID),
    CONSTRAINT FK_COURSE_INSTRUCTOR FOREIGN KEY (INSTRUCTOR_ID) 
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
);


-- ENROLLMENTS table
CREATE TABLE ENROLLMENTS (
    ENROLLMENT_ID NUMBER(10) PRIMARY KEY,
    STUDENT_ID NUMBER(10),
    COURSE_ID NUMBER(10),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    GRADE VARCHAR2(2),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY (STUDENT_ID) 
    REFERENCES STUDENTS(STUDENT_ID),
    CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY (COURSE_ID) 
    REFERENCES COURSES(COURSE_ID)
);



SELECT * FROM DEPARTMENT;
SELECT * FROM STUDENTS;
SELECT * FROM COURSES;
SELECT * FROM ENROLLMENTS;





        