

CREATE TABLE MANUFACTURER(
        MANUFACTURER_ID NUMBER(10) PRIMARY KEY,
        MANU_NAME  VARCHAR2(50),
        COUNTRY VARCHAR2(50),
        FOUNDED_YEAR NUMBER(4),
        NET_WORTH  NUMBER(15,2)
);


CREATE TABLE CarMODEL(
       MODEL_ID NUMBER(10) PRIMARY KEY,
       MODEL_NAME VARCHAR2(100),
       LAUNCH_YEAR NUMBER(4),
       ENGINE_TYPE VARCHAR2(50),
       CAR_CATEGORY VARCHAR(50),
       MANUFACTURER_ID NUMBER(10),
       CONSTRAINT FK_MODEL_MANUFACTURER 
       FOREIGN KEY (MANUFACTURER_ID)
         REFERENCES MANUFACTURER(MANUFACTURER_ID)
);


CREATE TABLE PLANTS (
        PLANT_ID NUMBER(10) PRIMARY KEY,
        MANUFACTURER_ID NUMBER(10),
        LOCATION VARCHAR2(100),
        COUNTRY VARCHAR2(50),
        OPEN_YEAR NUMBER(4),
        EMPLOYEES VARCHAR2(100),
        CONSTRAINT FK_PLANTS_MANUFACTURER
        FOREIGN KEY(MANUFACTURER_ID)
          REFERENCES MANUFACTURER(MANUFACTURER_ID)
);


CREATE TABLE SALES(

      SALE_ID NUMBER(10) PRIMARY KEY,
      MODEL_ID NUMBER(10),
      REGION VARCHAR2(50),
      SALE_YEAR NUMBER(4),
      UNIT_SOLD NUMBER,
      REVENUE NUMBER(15,2),
      CONSTRAINT FK_SALE_MODEL
      FOREIGN KEY(MODEL_ID)
      REFERENCES CarMODEL(MODEL_ID)
);


CREATE TABLE FEATURES(
      FEATURE_ID NUMBER(10) PRIMARY KEY,
      MODEL_ID NUMBER(10),
      FEATURE_NAME VARCHAR2(100),
      CONSTRAINT FK_FEATURES_MODEL
      FOREIGN KEY(MODEL_ID)
       REFERENCES  CarMODEL(MODEL_ID)
);


CREATE TABLE CUSTOMER(
     CUSTOMER_ID NUMBER(10) PRIMARY KEY,
     NAME VARCHAR2(100),
     COUNTRY VARCHAR2(50),
     MODEL_ID NUMBER(10),
     PURCHASE_DATE DATE,
     CONSTRAINT FK_CUSTOMER_MODEL
     FOREIGN KEY(MODEL_ID)
       REFERENCES  CarMODEL(MODEL_ID)
     
);


CREATE TABLE DEALERS(
    DEALER_ID NUMBER PRIMARY KEY,
    NAME  VARCHAR2(100),
    REGION VARCHAR2(100),
    CONTACT_EMAIL VARCHAR2(100)
);


CREATE TABLE MAINTAINANCE_RECORDS(
    MAINTAINANCE_ID NUMBER(10) PRIMARY KEY,
    DEALER_ID NUMBER(10),
    SERVICE_DATE DATE,
    SERVICE_TYPE VARCHAR2(100),
    COST NUMBER (10,2),
    CUSTOMER_ID NUMBER(10),
    MODEL_ID NUMBER(10),
    CONSTRAINT FK_MAINTAINANCE_CUSTOMER
     FOREIGN KEY (CUSTOMER_ID)
     REFERENCES CUSTOMER(CUSTOMER_ID),
     
    CONSTRAINT FK_MAINTAINANCE_MODEL
     FOREIGN KEY (MODEL_ID)
     REFERENCES CARMODEL(MODEL_ID),
    
    CONSTRAINT FK_MAINTAINANCE_DEALER
    FOREIGN KEY(DEALER_ID)
       REFERENCES DEALERS(DEALER_ID)
);